# Generated by Django 4.0.6 on 2022-07-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0008_alter_cartoonimg_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonimg',
            name='p_cart',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='cartoonimg',
            name='p_edge',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
