# Generated by Django 4.0.6 on 2022-07-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0003_rename_photo_cartoonimg_photo_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartoonimg',
            old_name='photo_cart',
            new_name='p_cart',
        ),
    ]
