# Generated by Django 4.0.6 on 2022-07-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0004_rename_photo_cart_cartoonimg_p_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoonimg',
            name='p_edge',
            field=models.ImageField(null=True, upload_to='edge'),
        ),
        migrations.AddField(
            model_name='cartoonimg',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='cartoonimg',
            name='p_cart',
            field=models.ImageField(null=True, upload_to='cartoon'),
        ),
    ]
