# Generated by Django 4.0.6 on 2022-07-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0005_cartoonimg_p_edge_cartoonimg_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartoonimg',
            options={'ordering': ['photo', 'p_edge', 'p_cart']},
        ),
    ]
