# Generated by Django 4.0.6 on 2022-07-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0006_alter_cartoonimg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartoonimg',
            options={},
        ),
    ]
