# Generated by Django 4.0.6 on 2022-07-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0007_alter_cartoonimg_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartoonimg',
            table='cartoonimg',
        ),
    ]
